### ISSUE TITLE
setup install error with updated development environment

### ISSUE THREAD

**Issue by louking** [louking/runningclub#66]
```
C:\Users\lking\Documents\Lou's Software\projects\runningclub>python runningclub\setup.py install
running install
install_dir C:\Users\lking\Anaconda2\Lib\site-packages\
running bdist_egg
running egg_info
writing requirements to runningclub.egg-info\requires.txt
writing runningclub.egg-info\PKG-INFO
writing top-level names to runningclub.egg-info\top_level.txt
writing dependency_links to runningclub.egg-info\dependency_links.txt
writing entry points to runningclub.egg-info\entry_points.txt
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'runningclub.egg-info\SOURCES.txt'
writing manifest file 'runningclub.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying runningclub\genagtables.py -> build\lib\runningclub
copying runningclub\setup.py -> build\lib\runningclub
copying runningclub\version.py -> build\lib\runningclub
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\agegrade.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\analyzeeventmembers.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\analyzemembership.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\clubmember.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\comparedb2fb.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\config.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\eventmerchandise2order.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\exportresults.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\findmembers.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\fsrcresult-old.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\genagtables.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\getresultsmembers.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\importmembers.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\importraces.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\importresults.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\listraces.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\membershipcleanup.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\modifymembers.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\modifyraces.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\modifyresults.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\racedb.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\racefile.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\raceresults.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\racingteamresults.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\rcadminapprove.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\rcadminconfig.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\rcuserconfig.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\render.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\renderrace.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\renderstandings.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\runningaheadmembers.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\setup.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\summarizemembers.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\updatemembers.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\updateraces.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\updateresults.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\userpw.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\version.py -> build\bdist.win-amd64\egg\runningclub
copying build\lib\runningclub\__init__.py -> build\bdist.win-amd64\egg\runningclub
byte-compiling build\bdist.win-amd64\egg\runningclub\agegrade.py to agegrade.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\analyzeeventmembers.py to analyzeeventmembers.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\analyzemembership.py to analyzemembership.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\clubmember.py to clubmember.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\comparedb2fb.py to comparedb2fb.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\config.py to config.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\eventmerchandise2order.py to eventmerchandise2order.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\exportresults.py to exportresults.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\findmembers.py to findmembers.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\fsrcresult-old.py to fsrcresult-old.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\genagtables.py to genagtables.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\getresultsmembers.py to getresultsmembers.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\importmembers.py to importmembers.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\importraces.py to importraces.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\importresults.py to importresults.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\listraces.py to listraces.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\membershipcleanup.py to membershipcleanup.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\modifymembers.py to modifymembers.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\modifyraces.py to modifyraces.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\modifyresults.py to modifyresults.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\racedb.py to racedb.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\racefile.py to racefile.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\raceresults.py to raceresults.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\racingteamresults.py to racingteamresults.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\rcadminapprove.py to rcadminapprove.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\rcadminconfig.py to rcadminconfig.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\rcuserconfig.py to rcuserconfig.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\render.py to render.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\renderrace.py to renderrace.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\renderstandings.py to renderstandings.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\runningaheadmembers.py to runningaheadmembers.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\setup.py to setup.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\summarizemembers.py to summarizemembers.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\updatemembers.py to updatemembers.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\updateraces.py to updateraces.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\updateresults.py to updateresults.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\userpw.py to userpw.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\version.py to version.pyc
byte-compiling build\bdist.win-amd64\egg\runningclub\__init__.py to __init__.pyc
installing package data to build\bdist.win-amd64\egg
running install_data
copying runningclub\database.pyc -> build\bdist.win-amd64\egg\runningclub
copying runningclub\database_script.pyc -> build\bdist.win-amd64\egg\runningclub
creating build\bdist.win-amd64\egg\runningclub\doc
creating build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\agegrade.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\clubmember.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\docsetup.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\importmembers.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\importraces.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\importresults.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\index.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\installation.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\listraces.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\modindex.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\racedb.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\racefile.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\raceresults.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\releasenotes.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\render.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\renderrace.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\renderstandings.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\versioning.rst -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\raceresultsformat.html -> build\bdist.win-amd64\egg\runningclub\doc\source
copying runningclub\doc\source\conf.py -> build\bdist.win-amd64\egg\runningclub\doc\source
creating build\bdist.win-amd64\egg\runningclub\doc\build
creating build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\agegrade.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\clubmember.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\docsetup.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\genindex.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\index.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\installation.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\listraces.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\modindex.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\py-modindex.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\racedb.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\racefile.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\raceresults.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\releasenotes.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\render.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\renderrace.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\renderstandings.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\search.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\updatemembers.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\updateraces.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\updateresults.html -> build\bdist.win-amd64\egg\runningclub\doc\build\html
copying runningclub\doc\build\html\searchindex.js -> build\bdist.win-amd64\egg\runningclub\doc\build\html
creating build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\agegrade.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\clubmember.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\docsetup.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\index.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\installation.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\listraces.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\modindex.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\racedb.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\racefile.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\raceresults.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\releasenotes.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\render.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\renderrace.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\renderstandings.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\updatemembers.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\updateraces.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
copying runningclub\doc\build\html\_sources\updateresults.txt -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_sources
creating build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\basic.css -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\default.css -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\pygments.css -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\doctools.js -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\jquery.js -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\searchtools.js -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\sidebar.js -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\underscore.js -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\websupport.js -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\comment-bright.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\comment-close.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\comment.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\down-pressed.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\down.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\file.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\minus.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\plus.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\up-pressed.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
copying runningclub\doc\build\html\_static\up.png -> build\bdist.win-amd64\egg\runningclub\doc\build\html\_static
creating build\bdist.win-amd64\egg\runningclub\doc\build\html\_images
creating build\bdist.win-amd64\egg\EGG-INFO
installing scripts to build\bdist.win-amd64\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
copying and adjusting runningclub\genagtables.py -> build\scripts-2.7
creating build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\agegrade.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\analyzeeventmembers.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\analyzemembership.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\eventmerchandise2order.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\exportresults.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\genagtables.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\getresultsmembers.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\importmembers.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\importraces.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\importresults.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\listraces.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\modifymembers.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\modifyraces.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\modifyresults.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\racingteamresults.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\rcadminapprove.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\rcadminconfig.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\rcuserconfig.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\renderrace.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\renderstandings.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\summarizemembers.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\updatemembers.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\updateraces.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying build\scripts-2.7\updateresults.py -> build\bdist.win-amd64\egg\EGG-INFO\scripts
copying runningclub.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying runningclub.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying runningclub.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying runningclub.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying runningclub.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying runningclub.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying runningclub.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating 'dist\runningclub-1.9.5rc1-py2.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing distribute-0.6.14-py2.7.egg
creating c:\users\lking\anaconda2\lib\site-packages\distribute-0.6.14-py2.7.egg
Extracting distribute-0.6.14-py2.7.egg to c:\users\lking\anaconda2\lib\site-packages
Adding distribute 0.6.14 to easy-install.pth file
Installing easy_install-script.py script to C:\Users\lking\Anaconda2\Scripts
Installing easy_install.exe script to C:\Users\lking\Anaconda2\Scripts
Installing easy_install-2.7-script.py script to C:\Users\lking\Anaconda2\Scripts
Installing easy_install-2.7.exe script to C:\Users\lking\Anaconda2\Scripts

Installed c:\users\lking\anaconda2\lib\site-packages\distribute-0.6.14-py2.7.egg
Traceback (most recent call last):
  File "runningclub\setup.py", line 113, in <module>
    url = 'http://github.com/louking/runningclub',
  File "C:\Users\lking\Anaconda2\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Users\lking\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\lking\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "build\bdist.win-amd64\egg\setuptools\command\install.py", line 73, in run
  File "build\bdist.win-amd64\egg\setuptools\command\install.py", line 101, in do_egg_install
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 342, in run
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 562, in easy_install
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 614, in install_item
  File "build\bdist.win-amd64\egg\setuptools\command\easy_install.py", line 661, in process_distribution
TypeError: __init__() takes exactly 2 arguments (4 given)

```

**Comment by louking** [comment]
deleted Lib\site-packages\distribute_setup.py, distribute-0.7.3.dist-info
