### ISSUE TITLE
mailchimpimport_rsu: ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by louking** [louking/runningclub#82]
```
Traceback (most recent call last):
  File "/var/www/www.steeplechasers.org/steepsvenv/bin/mailchimpimport_rsu", line 11, in <module>
    load_entry_point('runningclub==1.11.2', 'console_scripts', 'mailchimpimport_rsu')()
  File "/var/www/www.steeplechasers.org/steepsvenv/lib/python2.7/site-packages/runningclub-1.11.2-py2.7.egg/runningclub/mailchimpimport_rsu.py", line 348, in main
    importmembers(args.configfile, debug=args.debug, stats=args.stats)
  File "/var/www/www.steeplechasers.org/steepsvenv/lib/python2.7/site-packages/runningclub-1.11.2-py2.7.egg/runningclub/mailchimpimport_rsu.py", line 202, in importmembers
    lists = client.lists.all(get_all=True, fields="lists.name,lists.id")
  File "/var/www/www.steeplechasers.org/steepsvenv/lib/python2.7/site-packages/mailchimp3/entities/lists.py", line 187, in all
    return self._iterate(url=self._build_path(), **queryparams)
  File "/var/www/www.steeplechasers.org/steepsvenv/lib/python2.7/site-packages/mailchimp3/baseapi.py", line 60, in _iterate
    result = self._mc_client._get(url=url, offset=0, count=1000, **queryparams)
  File "/var/www/www.steeplechasers.org/steepsvenv/lib/python2.7/site-packages/mailchimp3/mailchimpclient.py", line 29, in wrapper
    return fn(self, *args, **kwargs)
  File "/var/www/www.steeplechasers.org/steepsvenv/lib/python2.7/site-packages/mailchimp3/mailchimpclient.py", line 157, in _get
    raise MailChimpError(r.json())
  File "/var/www/www.steeplechasers.org/steepsvenv/lib/python2.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by louking** [comment]
this seems to have been a transient problem with mailchimp -- wasn't reproducible and didn't happen the next day
